### ISSUE TITLE
Support hex addresses in monitor window

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#10]
when option "View" » "Hex Numbers" is selected, monitor window shows "Address" column in Hex but CALL, JR, JP , etc .. instructions still show input address in decimal.

Se last instruction in following screenshot
![image](https://cloud.githubusercontent.com/assets/13542000/8937706/20a755f6-3552-11e5-9409-df789b6b1009.png)

NOTE: Address are easily readable in hex from "bytes" column, if one knows how instructions are coded (just need to swap the correct bytes), but it would be more consistent to have address in "instruction" column also represented in hex, when hex is selected.

**Comment by ArjunNair** [comment]
Fixed.
