### ISSUE TITLE
Memory Variable View

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#12]
Currently there is a "Memory viewer" window, that allows to check memory contents.

However, it would be really helpful to be able to define:
- a memory address
- optionally a name

and the have a list of these pairs, and corresponding memory contents, listed in a new "watch" window.

These items could be loaded, base on symbols (address, that have a name), to defined these view variables.

Every time we hit a breakpoint or step debug, this window contents (memory values) are updated.

**Comment by ArjunNair** [comment]
Added a Watch Window tool to the Debugger.
