### ISSUE TITLE
After changing ROM file to something unsupported, Zero will fail to re-start.

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#18]
I was trying to test a Cartridge ROM (QBERT), and using Zero GUI, browsed to a "QBert.bin" file (not a .ROM file).

It failed to load, asked to select a folder for ROMs, which I tried to give the original Zero "roms" folder, but it failed again, and quit.

On restart of Zero, it has no ROM, so it complains and enters the same process to define a correct ROM, but fails again and again. IT doesn't seem to recognize it's own "roms" folder.

I had a look at "Zero.exe.config" file, but it's not being used, since it's modified date is older than it's create date.

It's probably using Windows Registry to keep it's settings, but I haven't found it's registry folder or key yet.

Resuming, I can't run ZERO now, unless I re-install.

Fix or workaround please, since I plan to test a lot of ROMs.

**Comment by Rui1973Martins** [comment]
I took a look at ZiggyWin/ZiggyWin/Form1.cs and apparently the problem surfaces, because I entered a filename complete with path, but code always appends "config.PathRoms" or (Application.StartupPath + "\\roms\\" ), so it seems it's not possible to load ROMs from other locations, besides these two.

Next, I'll check where config is loaded, to see if I can find a quick workaround.

**Comment by Rui1973Martins** [comment]
Copying the previously setup Qbert.bin file, makes Zero startup. but soon after a popup form appears asking to save a .TAP.

**Comment by Rui1973Martins** [comment]
After successful startup, one can easily enter into GUI settings, and change the ROM to a standard one.

Alternativelly, opening a TZX file by double clicking, makes application startup too, allowing to also change settings.

**Comment by ArjunNair** [comment]
I've added a fix for the startup issue. Zero no longer asks for the ROM folder if it finds it can't load a ROM on startup. Instead it asks you to point it to a ROM _file_  that it can try and use for the current spectrum model.

Also added is an option to disable tape traps when specifying ROMs to use. This will fix issues with Zero trying to trap tape routines on non-standard ROM's.
