### ISSUE TITLE
Is there a way to save a BASIC program that you have input via keyboard?

### ISSUE THREAD

**Issue by lmendo** [ArjunNair/Zero-Emulator#19]
I don't mean saving a snapshot of the whole computer state; just the program. Thanks!

**Comment by ArjunNair** [comment]
You can save it out like a normal tape file using the SAVE command in BASIC (eg: SAVE "myprog").  You will be asked for a tape file to save to just before the actual save process. This will save out a .tap file.

**Comment by lmendo** [comment]
Thank you
