### ISSUE TITLE
Joystick settings are forgotten on quit

### ISSUE THREAD

**Issue by Hexaae** [ArjunNair/Zero-Emulator#22]
Zero.exe 0.7.1
Even if I set as _Input Devices>Joystick_ 
joy1: SPEED-LINK Competition Pro
emulates: Kempston
and Save, on next Zero.exe restart these info will be lost and I have to reconfigure the input device every time.

**Comment by Hexaae** [comment]
As far as I can read in 0.7.2 What's new:
_+ Joysticks are now remembered between emulator sessions and automatically enabled on startup, if found._
this should have been already solved...?

**Comment by ArjunNair** [comment]
Yes, but v0.7.2 is WIP.
