### ISSUE TITLE
Unable to run emulator from Visual Studio 2017

### ISSUE THREAD

**Issue by Cthutu** [ArjunNair/Zero-Emulator#25]
I am able to run zero.exe when built from VS2017 by double-clicking on the exe from file explorer.  However, I am unable to run from visual studio as it crashes (an exception) when instantiating Form1.  I've installed the DirectX SDK.  Is there something I am doing wrong?

**Comment by ArjunNair** [comment]
What's the exception that it throws?

**Comment by ArjunNair** [comment]
Closing the issue due to no response.
