### ISSUE TITLE
Is is possible to properly reference resources int the project/solution ?

### ISSUE THREAD

**Issue by r618** [ArjunNair/Zero-Emulator#26]
i.e. making the references relative to the project -
VS can't find them ;/ :

Error	CS1719	Error opening Win32 resource file 'C:\Users\arjun\Documents\Zero-Emulator\ZiggyWin\ZiggyWin\zeroIconResource.res' -- 'Could not find a part of the path 'C:\Users\arjun\Documents\Zero-Emulator\ZiggyWin\ZiggyWin\zeroIconResource.res'.'	ZeroWin	C:\Users\user01\Downloads\zxsp\Zero-Emulator-master\ZiggyWin\ZiggyWin\CSC	1	Active

![image](https://user-images.githubusercontent.com/83213/39596520-ecb48d76-4f12-11e8-9e4f-93badd2c590d.png)

**Comment by r618** [comment]
(I probably conflated two issues there, build wants a .res file, there are only images in the screenshot)

**Comment by Specchum** [comment]
I get this error also when trying to run the solution in VS2017

**Comment by ArjunNair** [comment]
I've removed the stale references in the Resources folder (they aren't required). I've also changed the way the icon reference is used in the project. These should fix both the mentioned issues. Let me know if it works for you guys.

**Comment by r618** [comment]
compiles a-ok now - thanks mate ! )

**Comment by Specchum** [comment]
Yep, working now, thanks.
