### ISSUE TITLE
Watch Memory tool does not support address input in an App coherent form

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#31]
The only possible address input is decimal.

This input should be using a standardized function to work like the other address inputs, that also support HEX input, in the format: $FFFF

By the way this function should also accept HEX in the format #FFFF, since many assembler of the 80's also did.
And Pasmo also does support this #FFFF format.

**Comment by ArjunNair** [comment]
Done both the things.
