### ISSUE TITLE
Load Symbols ... Should parse the symbol value in any of the formats supported by the Emulator

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#35]
The emulator supports decimal and hex ($FFFF format).
Hopefully in the near future it will also suport HEX (#FFFF format).

However, CSV value column parsing is only accepting a decimal value.
This value parsing should be coherent across all features of the Emulator.

**I would also like to ask for a new feature: to also support parsing regular assembly language value listings, like the ones generated by Pasmo, that uses the EQU keyword, instead of a comma.**  (should be an easy thing to implement)

Pasmo sample:
> BLACK		EQU 00000H
> BLUE		EQU 00001H
> CYAN		EQU 00005H
> GREEN		EQU 00004H
> MAGENTA		EQU 00003H
> RED		EQU 00002H
> WHITE		EQU 00007H
> YELLOW		EQU 00006H
> BRIGHT		EQU 00040H
> FLASH		EQU 00080H

NOTE: Pasmo uses yet another format for HEX number, with a trailing H.
If that could also be supported accross the Emulator it would be great.

**Comment by ArjunNair** [comment]
Hex format support has been added (both $ and #). I don't plan to support Pasmo specific formats. It should be easy enough to replace EQU with , in any half decent text editor. :)
