### ISSUE TITLE
License for binary is still non-commercial

### ISSUE THREAD

**Issue by vlna** [ArjunNair/Zero-Emulator#4]
Please update or add explanation in README.md

see https://github.com/ArjunNair/Zero-Emulator/blob/master/run/License.txt

Thx.

**Comment by ArjunNair** [comment]
Done. Thx!






Sent from Windows Mail





From: vlna
Sent: ‎Sunday‎, ‎19‎ ‎April‎ ‎2015 ‎15‎:‎17
To: ArjunNair/Zero-Emulator





Please update or add explanation in README.md

see https://github.com/ArjunNair/Zero-Emulator/blob/master/run/License.txt

Thx.

**Comment by ArjunNair** [comment]
License updated.
