### ISSUE TITLE
Doesn't compile with the SlimDX library

### ISSUE THREAD

**Issue by ElasticCoder** [ArjunNair/Zero-Emulator#40]
The DirectSound library and SDK is deprecated, and I didn't want to install it, so I tried to compile with the SOUND_SLIMDX preprocessor directive. 

I had to install the SlimDX Nuget package.

However the code fails to compile with:

```
Error CS1061	'SoundManager' does not contain a definition for 'LockBuffer' and no accessible extension method 'LockBuffer' accepting a first argument of type 'SoundManager' could be found (are you missing a using directive or an assembly reference?)	Speccy	C:\source\Zero-Emulator\Ziggy\Speccy\zxSpectrum.cs	7924	Active

```

The LockBuffer and UnlockBuffer methods are only available with the DirectX mode, but are called from common code.

**Comment by ArjunNair** [comment]
SlimDX itself hasn't been updated for the past 11 years, so in a sense both are dead. *shrug*

The reason I moved to DirectSound from SlimDX was that there were some issues using the library back then. One of them was audio playback wasn't smooth for some users. The other was, if I remember correctly, some issue with distributing the SlimDX runtime package. 

Anyway, currently I don't see a way around the DirectSound issue unless you're willing to overhaul the sound streaming code to play nice with SlimDX. The core will have to be updated to use the SlimDX library too, of course.
