### ISSUE TITLE
Arcade joystick detected but not saved

### ISSUE THREAD

**Issue by Hexaae** [ArjunNair/Zero-Emulator#41]
![image](https://user-images.githubusercontent.com/8591462/157973522-49b0fc31-9d5f-4e9b-b0d1-e3982468b070.png)

Whenever I try to save it gets reset to None so I can't use my arcade USB joystick 'Hori Fighting Stick Mini' (seen as DPAD for stick directions).
Zero 0.8, Windows 10

**Comment by ArjunNair** [comment]
Pushed code to fix the bug. Thanks!
