### ISSUE TITLE
[Feature Request] Provide an option to turn off accelerated loading

### ISSUE THREAD

**Issue by wibblemonkey** [ArjunNair/Zero-Emulator#47]
Zero loads all TZX and TAP files in an accelerated manner - given that one of the goals for this emulator is to be "highly accurate", it would be good if this was an option that could be turned off for a more authentic Spectrum loading experience.

**Comment by ArjunNair** [comment]
Accelerated and edge loading can be turned on/off via the Tape Browser window.

**Comment by wibblemonkey** [comment]
I had turned off Fast Load but not Edge Load. Thanks.
