### ISSUE TITLE
[Feature Request] Add options to control creation of log file

### ISSUE THREAD

**Issue by wibblemonkey** [ArjunNair/Zero-Emulator#48]
Whenever I start Zero by double-clicking an associated file like a .tzx or .z80, it creates a ZeroLog.txt file in the directory where the TZX or Z80 snapshot file is located.
Can you please provide an option to turn off the creation of this file and / or place them in a single location _e.g._ in a `Zero` folder in my `APPDATA` folder or `C:\ProgramData\Zero` or similar?

**Comment by ArjunNair** [comment]
Changed it so that a file called TempLog with date time stamp is now created in the app installation directory instead. This file is automatically deleted when application is quit gracefully.
