### ISSUE TITLE
Computer sleep breaks emulator

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#8]
If computer is left for a while and sleeps/hibernates, when it wakes up, emulator window has a big white background with a red cross and border on it, and emulation no longer works.

Probably related with system timers, that don't get fired after waked up, screen resources or something similar.

**Comment by Rui1973Martins** [comment]
Here is a sample screenshot of this issue.
![zero-bug](https://cloud.githubusercontent.com/assets/13542000/9005130/796e6f12-3773-11e5-98a1-07f2c28dd097.png)

An easy way to replicate the problem, I just found, it to just lock and unlock windows, using  windows key + "L" key.

**Comment by ArjunNair** [comment]
Fixed
