### ISSUE TITLE
Support loading of symbols for debug

### ISSUE THREAD

**Issue by Rui1973Martins** [ArjunNair/Zero-Emulator#9]
It would be very useful to be able to define a text file with a list of symbols, so that debugger memory locations for CALL, JP, JR, ... and memory (variables) could be replaced to aid debugging.

Sample listing of symbols
![image](https://cloud.githubusercontent.com/assets/13542000/8937352/bec4acdc-354f-11e5-9ec1-8722b40fbe86.png)

Then if symbols are loaded, we would get:

CALL BALLB
JR NZ, KBEND
JP EXIT

instead of:

CALL 25011
JR NZ, 24827
JP 24834

It would also be very nice to show labels in monitor window, column "address", next to it's value, using existing symbol definitions. It could be used to document ROM entry points too.

**Comment by Rui1973Martins** [comment]
You already seem to support symbol replacement, related with ROM or BASIC addresses.

FRAMES for example.
![image](https://cloud.githubusercontent.com/assets/13542000/8937729/47e92252-3552-11e5-9ab1-87cfb4070ae7.png)

So it's just a matter of providing a file load mechanism to merge a few more definitions.

**Comment by ArjunNair** [comment]
That's a good idea!

**Comment by ArjunNair** [comment]
This feature has now been added.

**Comment by sky-ruimartins** [comment]
Cool
I'll try it, as soon as possible.

**Comment by sky-ruimartins** [comment]
I just took a quick look at the code, loadSymbolsToolStripMenuItem_Click, and it seems this will not work very well for 128K machines, or any machine that uses memory banks.
But it can depend a lot on how the labels are defined.

I would probably support memory locations larger than 65535, by including some reference to the memory bank, and the relative memory position.

The parsing also seems limited to regular ints (base 10), without support for Hex numbers for example.

**Comment by sky-ruimartins** [comment]
I would also suggest that you refactor the loading/parsing of the file, into a specific re-usable function, so that it can be triggered from somewhere else, like for example, by searching if the symbol file exists with the same name but different extension, than the loaded file.
